export type Rarity = 'Common' | 'Rare' | 'Legendary' | 'Mythical'

export type Fruit = {
  id: string
  name: string
  image: string
  price: number
  priceUSD: number
  stock: number
  rarity: Rarity
  blurb: string
  featured?: boolean
}

const MYTHICAL = '/fruits/premium/'
const LEGENDARY = '/fruits/legendary/'
const RARE = '/fruits/rare/'
const COMMON = '/fruits/common/'

export const fruits: Fruit[] = [
  // ── Mythical ──
  {
    id: 'kitsune',
    name: 'Kitsune',
    image: `${MYTHICAL}Kitsune.png`,
    price: 10,
    priceUSD: 2.94,
    stock: 24,
    rarity: 'Mythical',
    blurb: 'Zorro de nueve colas.',
    featured: true,
  },
  {
    id: 'tiger',
    name: 'Tiger',
    image: `${MYTHICAL}Tiger.png`,
    price: 4.50,
    priceUSD: 1.32,
    stock: 15,
    rarity: 'Mythical',
    blurb: 'Felino de combate.',
    featured: true,
  },
  {
    id: 'yeti',
    name: 'Yeti',
    image: `${MYTHICAL}Yeti.png`,
    price: 4.50,
    priceUSD: 1.32,
    stock: 6,
    rarity: 'Mythical',
    blurb: 'Bestia de hielo.',
    featured: true,
  },
  {
    id: 'lobo',
    name: 'Lobo',
    image: `${MYTHICAL}Lobo.png`,
    price: 21,
    priceUSD: 6.18,
    stock: 7,
    rarity: 'Mythical',
    blurb: 'Lobo salvaje de batalla.',
    featured: true,
  },
  {
    id: 'fiend-yeti',
    name: 'Fiend Yeti',
    image: `${MYTHICAL}Fiend_Yeti.png`,
    price: 20,
    priceUSD: 5.88,
    stock: 3,
    rarity: 'Mythical',
    blurb: 'Yeti oscuro y poderoso.',
  },
  {
    id: 'rumble-verde',
    name: 'Rumble Verde',
    image: `${MYTHICAL}Rumble_Verde.png`,
    price: 11.50,
    priceUSD: 3.38,
    stock: 10,
    rarity: 'Mythical',
    blurb: 'Tormenta de energia verde.',
  },
  {
    id: 'rumble-amarilla',
    name: 'Rumble Amarilla',
    image: `${MYTHICAL}Rumble_Amarilla.png`,
    price: 33,
    priceUSD: 9.71,
    stock: 2,
    rarity: 'Mythical',
    blurb: 'Rayo amarillo devastador.',
  },
  {
    id: 'super-spirit-pain',
    name: 'Super Spirit Pain',
    image: `${MYTHICAL}Super_Spirit_Pain.png`,
    price: 33,
    priceUSD: 9.71,
    stock: 1,
    rarity: 'Mythical',
    blurb: 'Espiritu supremo del dolor.',
  },
  {
    id: 'divine-portal',
    name: 'Divine Portal',
    image: `${MYTHICAL}Divine_Portal.png`,
    price: 26,
    priceUSD: 7.65,
    stock: 1,
    rarity: 'Mythical',
    blurb: 'Portal divino dimensional.',
  },
  {
    id: 'portal',
    name: 'Portal',
    image: `${MYTHICAL}portal.png`,
    price: 22,
    priceUSD: 6.47,
    stock: 3,
    rarity: 'Mythical',
    blurb: 'Teletransportate a traves del espacio.',
  },
  {
    id: 'rumble',
    name: 'Rumble',
    image: `${MYTHICAL}rumble.png`,
    price: 15,
    priceUSD: 4.41,
    stock: 5,
    rarity: 'Mythical',
    blurb: 'El poder del trueno en su maxima expresion.',
  },
  // ── Legendary ──
  {
    id: 'dragon',
    name: 'Dragon',
    image: `${LEGENDARY}control.png`,
    price: 45,
    priceUSD: 13.24,
    stock: 2,
    rarity: 'Legendary',
    blurb: 'Bestia alada de fuego y poder absoluto.',
    featured: true,
  },
  {
    id: 'leopard',
    name: 'Leopard',
    image: `${LEGENDARY}mammoth.png`,
    price: 38,
    priceUSD: 11.18,
    stock: 3,
    rarity: 'Legendary',
    blurb: 'Felino rapido como el rayo.',
  },
  {
    id: 'dough',
    name: 'Dough',
    image: `${LEGENDARY}dough.png`,
    price: 28,
    priceUSD: 8.24,
    stock: 5,
    rarity: 'Legendary',
    blurb: 'Masa maleable con poder destructivo.',
    featured: true,
  },
  {
    id: 'venom',
    name: 'Venom',
    image: `${LEGENDARY}venom.png`,
    price: 22,
    priceUSD: 6.47,
    stock: 4,
    rarity: 'Legendary',
    blurb: 'Veneno corrosivo que todo lo consume.',
  },
  {
    id: 'spirit',
    name: 'Spirit',
    image: `${LEGENDARY}spirit.png`,
    price: 18,
    priceUSD: 5.29,
    stock: 6,
    rarity: 'Legendary',
    blurb: 'Almas en pena al servicio de su portador.',
  },
  {
    id: 'control',
    name: 'Control',
    image: `${LEGENDARY}control.png`,
    price: 25,
    priceUSD: 7.35,
    stock: 3,
    rarity: 'Legendary',
    blurb: 'Manipula el espacio a tu antojo.',
  },
  {
    id: 'shadow',
    name: 'Shadow',
    image: `${LEGENDARY}shadow.png`,
    price: 15,
    priceUSD: 4.41,
    stock: 8,
    rarity: 'Legendary',
    blurb: 'Sombras que ocultan un poder letal.',
  },
  {
    id: 'mammoth',
    name: 'Mammoth',
    image: `${LEGENDARY}mammoth.png`,
    price: 12,
    priceUSD: 3.53,
    stock: 4,
    rarity: 'Legendary',
    blurb: 'Bestia prehistorica de fuerza colosal.',
  },
  {
    id: 't-rex',
    name: 'T-Rex',
    image: `${LEGENDARY}t_rex.png`,
    price: 10,
    priceUSD: 2.94,
    stock: 5,
    rarity: 'Legendary',
    blurb: 'El rey de los dinosaurios vuelve a la vida.',
  },
  // ── Rare ──
  {
    id: 'buddha',
    name: 'Buddha',
    image: `${RARE}buddha.png`,
    price: 12,
    priceUSD: 3.53,
    stock: 10,
    rarity: 'Rare',
    blurb: 'Iluminacion y fuerza descomunal.',
    featured: true,
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    image: `${RARE}phoenix.png`,
    price: 8,
    priceUSD: 2.35,
    stock: 12,
    rarity: 'Rare',
    blurb: 'Renace de las cenizas una y otra vez.',
  },
  {
    id: 'gravity',
    name: 'Gravity',
    image: `${RARE}gravity.png`,
    price: 9,
    priceUSD: 2.65,
    stock: 10,
    rarity: 'Rare',
    blurb: 'Domina la gravedad y aplasta a tus enemigos.',
  },
  {
    id: 'love',
    name: 'Love',
    image: `${RARE}love.png`,
    price: 5,
    priceUSD: 1.47,
    stock: 15,
    rarity: 'Rare',
    blurb: 'El poder del amor... y la destruccion.',
  },
  {
    id: 'blizzard',
    name: 'Blizzard',
    image: `${RARE}blizzard.png`,
    price: 7,
    priceUSD: 2.06,
    stock: 12,
    rarity: 'Rare',
    blurb: 'Tormenta de hielo que congela todo.',
  },
  {
    id: 'lightning',
    name: 'Lightning',
    image: `${RARE}lightning.png`,
    price: 6,
    priceUSD: 1.76,
    stock: 8,
    rarity: 'Rare',
    blurb: 'Rayos y centellas a tu disposicion.',
  },
  {
    id: 'diamond',
    name: 'Diamond',
    image: `${RARE}diamond.png`,
    price: 4,
    priceUSD: 1.18,
    stock: 12,
    rarity: 'Rare',
    blurb: 'Dureza inquebrantable como el diamante.',
  },
  {
    id: 'eagle',
    name: 'Eagle',
    image: `${RARE}eagle.png`,
    price: 4,
    priceUSD: 1.18,
    stock: 10,
    rarity: 'Rare',
    blurb: 'Aguila rapida de vista aguda.',
  },
  {
    id: 'ghost',
    name: 'Ghost',
    image: `${RARE}ghost.png`,
    price: 5,
    priceUSD: 1.47,
    stock: 8,
    rarity: 'Rare',
    blurb: 'Espectral e impredecible como un fantasma.',
  },
  {
    id: 'sand',
    name: 'Sand',
    image: `${RARE}sand.png`,
    price: 3,
    priceUSD: 0.88,
    stock: 15,
    rarity: 'Rare',
    blurb: 'Arena movediza que todo lo absorbe.',
  },
  {
    id: 'creation',
    name: 'Creation',
    image: `${RARE}creation.png`,
    price: 6,
    priceUSD: 1.76,
    stock: 6,
    rarity: 'Rare',
    blurb: 'Crea estructuras con puro poder.',
  },
  {
    id: 'spider',
    name: 'Spider',
    image: `${RARE}spider.png`,
    price: 3,
    priceUSD: 0.88,
    stock: 12,
    rarity: 'Rare',
    blurb: 'Telarana letal que atrapa a tus enemigos.',
  },
  {
    id: 'sound',
    name: 'Sound',
    image: `${RARE}sound.png`,
    price: 4,
    priceUSD: 1.18,
    stock: 10,
    rarity: 'Rare',
    blurb: 'Vibraciones sonoras con poder destructivo.',
  },
  // ── Common ──
  {
    id: 'flame',
    name: 'Flame',
    image: `${COMMON}flame.png`,
    price: 3,
    priceUSD: 0.88,
    stock: 20,
    rarity: 'Common',
    blurb: 'Llamas basicas pero efectivas.',
  },
  {
    id: 'ice',
    name: 'Ice',
    image: `${COMMON}ice.png`,
    price: 2.50,
    priceUSD: 0.74,
    stock: 25,
    rarity: 'Common',
    blurb: 'Hielo solido para congelar a tus rivales.',
  },
  {
    id: 'dark',
    name: 'Dark',
    image: `${COMMON}dark.png`,
    price: 4,
    priceUSD: 1.18,
    stock: 18,
    rarity: 'Common',
    blurb: 'Oscuridad que absorbe la luz.',
  },
  {
    id: 'light',
    name: 'Light',
    image: `${COMMON}light.png`,
    price: 3.50,
    priceUSD: 1.03,
    stock: 20,
    rarity: 'Common',
    blurb: 'Velocidad y destellos cegadores.',
  },
  {
    id: 'magma',
    name: 'Magma',
    image: `${COMMON}magma.png`,
    price: 5,
    priceUSD: 1.47,
    stock: 15,
    rarity: 'Common',
    blurb: 'Roca fundida que todo lo derrite.',
  },
  {
    id: 'bomb',
    name: 'Bomb',
    image: `${COMMON}bomb.png`,
    price: 1,
    priceUSD: 0.29,
    stock: 30,
    rarity: 'Common',
    blurb: 'Explosiones basicas pero devastadoras.',
  },
  {
    id: 'smoke',
    name: 'Smoke',
    image: `${COMMON}smoke.png`,
    price: 1.50,
    priceUSD: 0.44,
    stock: 25,
    rarity: 'Common',
    blurb: 'Cortina de humo que desorienta al rival.',
  },
  {
    id: 'spike',
    name: 'Spike',
    image: `${COMMON}spike.png`,
    price: 1.50,
    priceUSD: 0.44,
    stock: 25,
    rarity: 'Common',
    blurb: 'Puas afiladas para el combate cuerpo a cuerpo.',
  },
  {
    id: 'spin',
    name: 'Spin',
    image: `${COMMON}spin.png`,
    price: 1,
    priceUSD: 0.29,
    stock: 30,
    rarity: 'Common',
    blurb: 'Gira sin control como un tornado.',
  },
  {
    id: 'spring',
    name: 'Spring',
    image: `${COMMON}spring.png`,
    price: 1.50,
    priceUSD: 0.44,
    stock: 25,
    rarity: 'Common',
    blurb: 'Saltos elasticos y golpes sorpresivos.',
  },
  {
    id: 'blade',
    name: 'Blade',
    image: `${COMMON}blade.png`,
    price: 2,
    priceUSD: 0.59,
    stock: 20,
    rarity: 'Common',
    blurb: 'Cortes afilados como cuchillas.',
  },
  {
    id: 'rocket',
    name: 'Rocket',
    image: `${COMMON}rocket.png`,
    price: 1,
    priceUSD: 0.29,
    stock: 30,
    rarity: 'Common',
    blurb: 'Propulsion a maxima velocidad.',
  },
  {
    id: 'rubber',
    name: 'Rubber',
    image: `${COMMON}rubber.png`,
    price: 2,
    priceUSD: 0.59,
    stock: 20,
    rarity: 'Common',
    blurb: 'Cuerpo elastico que rebota cualquier ataque.',
  },
]

const rarityColors: Record<Rarity, { label: string; chip: string; glow: string; border: string }> = {
  Common: {
    label: 'Common',
    chip: 'border-zinc-600 bg-zinc-800/60 text-zinc-400',
    glow: 'rgba(113,113,122,0.3)',
    border: 'border-zinc-600/40',
  },
  Rare: {
    label: 'Rare',
    chip: 'border-purple-500/40 bg-purple-500/15 text-purple-400',
    glow: 'rgba(168,85,247,0.35)',
    border: 'border-purple-500/30',
  },
  Legendary: {
    label: 'Legendary',
    chip: 'border-orange-500/40 bg-orange-500/15 text-orange-400',
    glow: 'rgba(249,115,22,0.4)',
    border: 'border-orange-500/30',
  },
  Mythical: {
    label: 'Mythical',
    chip: 'border-red-500/40 bg-red-500/15 text-red-400',
    glow: 'rgba(239,35,60,0.5)',
    border: 'border-red-500/30',
  },
}

export function getRarityStyle(rarity: Rarity) {
  return rarityColors[rarity]
}

export const DISCORD_URL = 'https://discord.gg/aioniss'
export const TIKTOK_URL = 'https://tiktok.com/@aioniss'
