export type Rarity = 'Common' | 'Rare' | 'Legendary' | 'Mythical'

export type Fruit = {
  id: string
  name: string
  image: string
  price: number
  priceUSD: number
  stock: number
  rarity: Rarity
  blurb: string
  featured?: boolean
}

const STOCK = '/fruits/premium/'

export const fruits: Fruit[] = [
  // ── Mythical ──
  {
    id: 'kitsune',
    name: 'Kitsune',
    image: `${STOCK}Kitsune.png`,
    price: 10,
    priceUSD: 2.94,
    stock: 24,
    rarity: 'Mythical',
    blurb: 'Zorro de nueve colas.',
    featured: true,
  },
  {
    id: 'tiger',
    name: 'Tiger',
    image: `${STOCK}Tiger.png`,
    price: 4.50,
    priceUSD: 1.32,
    stock: 15,
    rarity: 'Mythical',
    blurb: 'Felino de combate.',
    featured: true,
  },
  {
    id: 'yeti',
    name: 'Yeti',
    image: `${STOCK}Yeti.png`,
    price: 4.50,
    priceUSD: 1.32,
    stock: 6,
    rarity: 'Mythical',
    blurb: 'Bestia de hielo.',
    featured: true,
  },
  {
    id: 'lobo',
    name: 'Lobo',
    image: `${STOCK}Lobo.png`,
    price: 21,
    priceUSD: 6.18,
    stock: 7,
    rarity: 'Mythical',
    blurb: 'Lobo salvaje de batalla.',
    featured: true,
  },
  {
    id: 'fiend-yeti',
    name: 'Fiend Yeti',
    image: `${STOCK}Fiend_Yeti.png`,
    price: 20,
    priceUSD: 5.88,
    stock: 3,
    rarity: 'Mythical',
    blurb: 'Yeti oscuro y poderoso.',
  },
  {
    id: 'rumble-verde',
    name: 'Rumble Verde',
    image: `${STOCK}Rumble_Verde.png`,
    price: 11.50,
    priceUSD: 3.38,
    stock: 10,
    rarity: 'Mythical',
    blurb: 'Tormenta de energia verde.',
  },
  {
    id: 'rumble-amarilla',
    name: 'Rumble Amarilla',
    image: `${STOCK}Rumble_Amarilla.png`,
    price: 33,
    priceUSD: 9.71,
    stock: 2,
    rarity: 'Mythical',
    blurb: 'Rayo amarillo devastador.',
  },
  {
    id: 'super-spirit-pain',
    name: 'Super Spirit Pain',
    image: `${STOCK}Super_Spirit_Pain.png`,
    price: 33,
    priceUSD: 9.71,
    stock: 1,
    rarity: 'Mythical',
    blurb: 'Espiritu supremo del dolor.',
  },
  {
    id: 'divine-portal',
    name: 'Divine Portal',
    image: `${STOCK}Divine_Portal.png`,
    price: 26,
    priceUSD: 7.65,
    stock: 1,
    rarity: 'Mythical',
    blurb: 'Portal divino dimensional.',
  },
  // ── Legendary ──
  {
    id: 'dragon',
    name: 'Dragon',
    image: `${STOCK}Kitsune.png`,
    price: 45,
    priceUSD: 13.24,
    stock: 2,
    rarity: 'Legendary',
    blurb: 'Bestia alada de fuego y poder absoluto.',
    featured: true,
  },
  {
    id: 'leopard',
    name: 'Leopard',
    image: `${STOCK}Tiger.png`,
    price: 38,
    priceUSD: 11.18,
    stock: 3,
    rarity: 'Legendary',
    blurb: 'Felino rapido como el rayo.',
  },
  {
    id: 'dough',
    name: 'Dough',
    image: `${STOCK}Yeti.png`,
    price: 28,
    priceUSD: 8.24,
    stock: 5,
    rarity: 'Legendary',
    blurb: 'Masa maleable con poder destructivo.',
    featured: true,
  },
  {
    id: 'venom',
    name: 'Venom',
    image: `${STOCK}Rumble_Verde.png`,
    price: 22,
    priceUSD: 6.47,
    stock: 4,
    rarity: 'Legendary',
    blurb: 'Veneno corrosivo que todo lo consume.',
  },
  {
    id: 'spirit',
    name: 'Spirit',
    image: `${STOCK}Super_Spirit_Pain.png`,
    price: 18,
    priceUSD: 5.29,
    stock: 6,
    rarity: 'Legendary',
    blurb: 'Almas en pena al servicio de su portador.',
  },
  {
    id: 'control',
    name: 'Control',
    image: `${STOCK}Divine_Portal.png`,
    price: 25,
    priceUSD: 7.35,
    stock: 3,
    rarity: 'Legendary',
    blurb: 'Manipula el espacio a tu antojo.',
  },
  {
    id: 'shadow',
    name: 'Shadow',
    image: `${STOCK}Lobo.png`,
    price: 15,
    priceUSD: 4.41,
    stock: 8,
    rarity: 'Legendary',
    blurb: 'Sombras que ocultan un poder letal.',
  },
  // ── Rare ──
  {
    id: 'buddha',
    name: 'Buddha',
    image: `${STOCK}Kitsune.png`,
    price: 12,
    priceUSD: 3.53,
    stock: 10,
    rarity: 'Rare',
    blurb: 'Iluminacion y fuerza descomunal.',
    featured: true,
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    image: `${STOCK}Fiend_Yeti.png`,
    price: 8,
    priceUSD: 2.35,
    stock: 12,
    rarity: 'Rare',
    blurb: 'Renace de las cenizas una y otra vez.',
  },
  {
    id: 'gravity',
    name: 'Gravity',
    image: `${STOCK}Yeti.png`,
    price: 9,
    priceUSD: 2.65,
    stock: 10,
    rarity: 'Rare',
    blurb: 'Domina la gravedad y aplasta a tus enemigos.',
  },
  {
    id: 'love',
    name: 'Love',
    image: `${STOCK}Divine_Portal.png`,
    price: 5,
    priceUSD: 1.47,
    stock: 15,
    rarity: 'Rare',
    blurb: 'El poder del amor... y la destruccion.',
  },
  {
    id: 'blizzard',
    name: 'Blizzard',
    image: `${STOCK}Yeti.png`,
    price: 7,
    priceUSD: 2.06,
    stock: 12,
    rarity: 'Rare',
    blurb: 'Tormenta de hielo que congela todo.',
  },
  // ── Common ──
  {
    id: 'flame',
    name: 'Flame',
    image: `${STOCK}Kitsune.png`,
    price: 3,
    priceUSD: 0.88,
    stock: 20,
    rarity: 'Common',
    blurb: 'Llamas basicas pero efectivas.',
  },
  {
    id: 'ice',
    name: 'Ice',
    image: `${STOCK}Yeti.png`,
    price: 2.50,
    priceUSD: 0.74,
    stock: 25,
    rarity: 'Common',
    blurb: 'Hielo solido para congelar a tus rivales.',
  },
  {
    id: 'dark',
    name: 'Dark',
    image: `${STOCK}Lobo.png`,
    price: 4,
    priceUSD: 1.18,
    stock: 18,
    rarity: 'Common',
    blurb: 'Oscuridad que absorbe la luz.',
  },
  {
    id: 'light',
    name: 'Light',
    image: `${STOCK}Divine_Portal.png`,
    price: 3.50,
    priceUSD: 1.03,
    stock: 20,
    rarity: 'Common',
    blurb: 'Velocidad y destellos cegadores.',
  },
  {
    id: 'magma',
    name: 'Magma',
    image: `${STOCK}Fiend_Yeti.png`,
    price: 5,
    priceUSD: 1.47,
    stock: 15,
    rarity: 'Common',
    blurb: 'Roca fundida que todo lo derrite.',
  },
]

const rarityColors: Record<Rarity, { label: string; chip: string; glow: string; border: string }> = {
  Common: {
    label: 'Common',
    chip: 'border-zinc-600 bg-zinc-800/60 text-zinc-400',
    glow: 'rgba(113,113,122,0.3)',
    border: 'border-zinc-600/40',
  },
  Rare: {
    label: 'Rare',
    chip: 'border-purple-500/40 bg-purple-500/15 text-purple-400',
    glow: 'rgba(168,85,247,0.35)',
    border: 'border-purple-500/30',
  },
  Legendary: {
    label: 'Legendary',
    chip: 'border-orange-500/40 bg-orange-500/15 text-orange-400',
    glow: 'rgba(249,115,22,0.4)',
    border: 'border-orange-500/30',
  },
  Mythical: {
    label: 'Mythical',
    chip: 'border-red-500/40 bg-red-500/15 text-red-400',
    glow: 'rgba(239,35,60,0.5)',
    border: 'border-red-500/30',
  },
}

export function getRarityStyle(rarity: Rarity) {
  return rarityColors[rarity]
}

export const DISCORD_URL = 'https://discord.gg/aioniss'
export const TIKTOK_URL = 'https://tiktok.com/@aioniss'
